---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-demo
  namespace: dev-environment
  labels:
    role: ingestion
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingest-demo
    spec:
      containers:
         - name: ingest-demo
           image: quay.io/humancellatlas/ingest-demo:v5_upgrade_and_wrapper_processes
           imagePullPolicy: Always
           env:
             - name: INGEST_API
               value: http://api.ingest.dev.data.humancellatlas.org:80
           ports:
             - containerPort: 5000
