---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo
  namespace: dev-environment
  labels:
    role: ingestion
spec:
  serviceName: "mongo-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-tmp
  template:
    metadata:
      labels:
        app: mongo-tmp
    spec:
      containers:
      - name: mongo
        image: mongo:3.4.3
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
