apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    role: ingestion
  name: ingest-archiver
  namespace: staging-environment
  selfLink: /apis/extensions/v1beta1/namespaces/staging-environment/deployments/ingest-archiver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingest-archiver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ingest-archiver
    spec:
      containers:
      - env:
        - name: INGEST_API
          value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
        - name: RABBITMQ_URL
          value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT}
        - name: RABBITMQ_ARCHIVAL_QUEUE
          value: ingest.archival.queue
        - name: RABBITMQ_SUBMITTED_EXCHANGE
          value: ingest.envelope.submitted.exchange
        - name: RABBITMQ_SUBMITTED_QUEUE
          value: ingest.envelope.submitted.queue
        - name: AAP_API_URL
          value: https://explore.api.aap.tsi.ebi.ac.uk/auth
        - name: AAP_API_DOMAIN
          value: self.hca-user
        - name: AAP_API_USER
          value: hcaingestd
        - name: USI_API_URL
          value: https://submission-dev.ebi.ac.uk
        - name: AAP_API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: aap-api-password
              name: api-keys
        image: quay.io/humancellatlas/ingest-archiver:v0.1.0.rc
        imagePullPolicy: Always
        name: ingest-archiver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
