apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: submission
  name: rabbit
  namespace: staging-environment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - image: rabbitmq:3-management-alpine
        name: rabbit
        ports:
        - containerPort: 5672
        - containerPort: 15672
