apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    role: test
  name: mock-upload
spec:
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 8080
  selector:
    app: mock-upload
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: test
  name: mock-upload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-upload
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mock-upload
    spec:
      containers:
      - env:
        - name: API_VERSION
          value: v1
        - name: RABBITMQ_HOST
          value: ${RABBIT_SERVICE_SERVICE_HOST}
        - name: RABBITMQ_PORT
          value: ${RABBIT_SERVICE_SERVICE_PORT}
        image: quay.io/humancellatlas/ingest-mock-upload-service:master_6d4a58b
        name: mock-upload
