apiVersion: v1
kind: Secret
metadata:
  name: auth-broker
data:
  client-id: PHJlZGFjdGVkPg==
  client-secret: PHJlZGFjdGVkPg==

---

apiVersion: v1
kind: Secret
metadata:
    name: api-keys
data:
    aap-api-password: PHJlZGFjdGVkPg==
    staging-api-key: PHJlZGFjdGVkPg==
