---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: validator-status-flipper
        labels:
                role: validation
                branch: master
spec:
        replicas: 1 
        strategy: 
                type: "RollingUpdate"
        template: 
                metadata:
                        labels:
                                app: validator-status-flipper
                                branch: master
                spec:
                        containers:
                                - name: validator-status-flipper
                                  image: rolando3794/validator-status-flipper:master
                                  env:
                                          - name: MONGO_URI
                                            value: mongodb://subs_rw:L5Iw4lUktqrF@mongos-hxvm7-usi-001.ebi.ac.uk:27117,mongos-hhvm7-usi-001.ebi.ac.uk:27217/admin
                                          - name: RABBIT_HOST
                                            value: mac-subs-001.ebi.ac.uk
                                          - name: RABBIT_PORT
                                            value: "5672"
