---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: validator-coordinator
        labels:
                role: validation
                branch: master
spec:
        replicas: 2 # tells deployment to run 2 pods matching the template
        strategy: # we should have a rolling update strategy i.e changes deployed automatically
                type: "RollingUpdate"
        template: # create pods using pod definition in this template
                metadata:
                        labels:
                                app: validator-coordinator
                                branch: master
                spec:
                        containers:
                                - name: validator-coordinator
                                  image: rolando3794/validator-coordinator:master
                                  env:
                                          - name: MONGO_URI
                                            value: mongodb://subs_rw:L5Iw4lUktqrF@mongos-hxvm7-usi-001.ebi.ac.uk:27117,mongos-hhvm7-usi-001.ebi.ac.uk:27217/admin
                                          - name: RABBIT_HOST
                                            value: mac-subs-001.ebi.ac.uk
                                          - name: RABBIT_PORT
                                            value: "5672"
