apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-exporter
  namespace: {{ .Values.environment }}-environment
spec:
  replicas: 15
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-exporter
    spec:
      containers:
      - env:
        - name: INGEST_API
          value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
        - name: RABBIT_URL
          value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
        - name: STAGING_API
          value: https://upload.{{ .Values.environment }}.data.humancellatlas.org
        - name: DSS_API
          value: https://dss.{{ .Values.environment }}.data.humancellatlas.org
        - name: BUNDLE_SCHEMA_BASE_URL
          value: http://schema.{{ .Values.environment }}.data.humancellatlas.org
        - name: INGEST_API_KEY
          valueFrom:
            secretKeyRef:
              key: staging-api-key
              name: api-keys
        - name: EXPORTER_AUTH_INFO
          valueFrom:
            secretKeyRef:
              key: exporter-auth-info
              name: api-keys
        image: quay.io/humancellatlas/ingest-exporter:{{ .Values.image }}
        imagePullPolicy: Always
        name: ingest-exporter
      dnsPolicy: Default
