---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-demo
  namespace: prod-environment
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy: 
    type: "RollingUpdate"
  template: 
    metadata:
      labels:
        app: ingest-demo
    spec:
      containers:
         - name: ingest-demo
           image: quay.io/humancellatlas/ingest-demo:v0.4.0.rc
           imagePullPolicy: Always
           env:
             - name: INGEST_API
               value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}
           ports:
             - containerPort: 5000
