apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ingest-backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: rdgoite/ingest-backup:latest
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secretAccessKey
            - name: S3_BUCKET
              value: ingest-backup
            - name: BACKUP_DIR
              value: dev
          restartPolicy: OnFailure
          
