apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ingest-backup
spec:
  schedule: "0 0-23/2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: quay.io/humancellatlas/ingest-backup:a99a2f9
            imagePullPolicy: Always
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: backup-keys
                  name: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: backup-keys
                  name: aws-secret-access-key
            - name: S3_BUCKET
              value: ingest-backup
            - name: BACKUP_DIR
              value: dev
          restartPolicy: OnFailure
          
