apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-broker
  namespace: {{ .Values.environment }}-environment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingest-broker
    spec:
      containers:
      - env:
        - name: INGEST_API
          value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
        image: quay.io/humancellatlas/ingest-broker:{{ .Values.image }}
        imagePullPolicy: Always
        name: ingest-broker
        ports:
        - containerPort: 5000
      dnsPolicy: Default
