apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-validator-js
  namespace: {{ .Values.environment }}-environment
spec:
  replicas: 15
  template:
    metadata:
      labels:
        app: ingest-validator-js
    spec:
      dnsPolicy: Default
      containers:
      - env:
        - name: INGEST_HOST
          value: $(INGEST_CORE_SERVICE_SERVICE_HOST)
        - name: INGEST_PORT
          value: $(INGEST_CORE_SERVICE_SERVICE_PORT)
        - name: RABBIT_HOST
          value: $(RABBIT_SERVICE_SERVICE_HOST)
        - name: RABBIT_PORT
          value: $(RABBIT_SERVICE_SERVICE_PORT_SERVICE)
        - name: UPLOAD_HOST
          value: upload.{{ .Values.environment }}.data.humancellatlas.org
        - name: UPLOAD_PORT
          value: "443"
        - name: UPLOAD_API_KEY
          valueFrom:
            secretKeyRef:
              key: staging-api-key
              name: api-keys
        image: quay.io/humancellatlas/ingest-validator-js:{{ .Values.image }}
        imagePullPolicy: Always
        name: ingest-validator
