---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-ontology
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy: 
    type: "RollingUpdate"
  template: 
    metadata:
      labels:
        app: ingest-ontology
    spec:
      containers:
         - name: ingest-ontology
           image: ingest-ontology:local
           ports:
             - containerPort: 8080
