---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: ingest-ontology-service
  name: ingest-ontology-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ebi-ols
  sessionAffinity: None
  type: NodePort
