apiVersion: v1
data:
  aap-api-password: PHJlZGFjdGVkPg==
  staging-api-key: PHJlZGFjdGVkPg==
kind: Secret
metadata:
  annotations: {}
  name: api-keys
  namespace: {{ .Values.environment }}-environment
type: Opaque
---
apiVersion: v1
data:
  aws-access-key-id: PHJlZGFjdGVkPg==
  aws-secret-access-key: PHJlZGFjdGVkPg==
kind: Secret
metadata:
  annotations: {}
  name: aws-keys
  namespace: {{ .Values.environment }}-environment
type: Opaque
