apiVersion: v1
data:
  aap-api-password: YWFwaW5nZXN0aGNhITIwMTc=
  staging-api-key: PASTE_SECRET_HERE
kind: Secret
metadata:
  annotations: {}
  name: api-keys
  namespace: staging-environment
type: Opaque
