apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-demo
  namespace: integration-environment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-demo
    spec:
      containers:
      - env:
        - name: INGEST_API
          value: http://api.ingest.integration.data.humancellatlas.org:80
        image: quay.io/humancellatlas/ingest-demo:stable_5
        imagePullPolicy: Always
        name: ingest-demo
        ports:
        - containerPort: 5000
