apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: test
  name: mock-upload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-upload
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mock-upload
    spec:
      containers:
      - name: mock-upload
        image: quay.io/humancellatlas/ingest-mock-upload-service:a613451
        env:
        - name: API_VERSION
          value: v1
        - name: RABBITMQ_HOST
          value: $(RABBIT_SERVICE_SERVICE_HOST)
        - name: RABBITMQ_PORT
          value: $(RABBIT_SERVICE_SERVICE_PORT)
        - name: DEBUG
          value: 'false'
        
