kind: Service
apiVersion: v1
metadata:
        name: "mongo-service"
spec:
        ports:
                - port: 27127
                  targetPort: 27127
        selector:
                app: mongo
