apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
  name: ingress-nginx-template
data:
  {{ (.Files.Glob "files/nginx.tmpl").AsConfig | indent 2 }}
