ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core
        hostname: api.ingest.testing.data.humancellatlas.org
      - service: ingest-broker
        hostname: ingest.dev.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:861229788715:certificate/bc640e02-86e7-4e1a-a9cc-034fbf4bd378

