# Default values for ingress-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# for subchart stable/nginx-ingress

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:861229788715:certificate/86982ec7-62da-4b70-a467-159386f0130f
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      targetPorts:
          https: http
  rbac:
    create: "true"
