apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: staging-environment
type: Opaque
data:
  staging-api-key: MEZkeU9jbFpLeGNXbWd0em9YcVFFYlcxMUVRNEhHL05XcXJjN1h5UEFVb0dzMnU2Vk15K1BDRGZ4cWFrTytldXUxcXcyY0RLdTl6MUtSd2pSMVpZSWRPOGJjYkUxbGY3M25tVU9vVG9vWnk2d3R1aVRCYUNhaXFRYjBIRisvNXc1SjhPNUNTMXJ2T0JvdkVoM25ENk15UmsvRm9zeWZUV3VNOUZ3SE4wUERjPQ==
  aap-api-password: YWFwaW5nZXN0aGNhITIwMTc=
