apiVersion: v1
kind: Service
metadata:
  labels:
    role: test
  name: secondary-analysis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8089
  selector:
    app: secondary-analysis
  sessionAffinity: None
  type: LoadBalancer
              
              
