apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    role: test
  name: mock-upload
spec:
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 8080
  selector:
    app: mock-upload
  sessionAffinity: None
  type: ClusterIP
