apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    role: test
  name: mock-upload
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: mock-upload
  sessionAffinity: None
  type: LoadBalancer
